version: '3'
services:
  mathematical_robotics:
    image: takumanakao/mathematical_robotics:latest
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ../../mathematical_robotics:/home/mathematical_robotics
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    working_dir: /home/mathematical_robotics
    tty: true
